package com.example.cinema.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Booking Entity - Core Business Logic
 * Simplified booking system focusing on essential booking functionality
 */
@Entity
@Table(name = "bookings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"user", "showtime"})
public class Booking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @NotNull(message = "Showtime is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "showtime_id", nullable = false)
    private Showtime showtime;

    @Positive(message = "Seats booked must be positive")
    @Column(name = "seats_booked", nullable = false)
    private Integer seatsBooked;

    @Positive(message = "Total amount must be positive")
    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    @Column(name = "booking_status")
    private BookingStatus bookingStatus = BookingStatus.CONFIRMED;

    @Column(name = "booking_reference", unique = true, nullable = false)
    private String bookingReference; // Auto-generated by DB trigger

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    // Utility methods
    public boolean canBeCancelled() {
        return BookingStatus.CONFIRMED.equals(bookingStatus) &&
               showtime != null && showtime.isUpcoming();
    }

    public boolean isConfirmed() {
        return BookingStatus.CONFIRMED.equals(bookingStatus);
    }

    public boolean isCancelled() {
        return BookingStatus.CANCELLED.equals(bookingStatus);
    }

    public void cancel() {
        this.bookingStatus = BookingStatus.CANCELLED;
    }

    public BigDecimal getPricePerSeat() {
        if (seatsBooked == null || seatsBooked == 0) {
            return BigDecimal.ZERO;
        }
        return totalAmount.divide(BigDecimal.valueOf(seatsBooked), 2, java.math.RoundingMode.HALF_UP);
    }

    public String getMovieTitle() {
        return showtime != null ? showtime.getMovieTitle() : "Unknown Movie";
    }

    public String getTheaterName() {
        return showtime != null ? showtime.getTheaterName() : "Unknown Theater";
    }

    public LocalDateTime getShowDateTime() {
        return showtime != null ? showtime.getShowDatetime() : null;
    }

    public String getUserName() {
        return user != null ? user.getFullName() : "Unknown User";
    }

    public String getUserEmail() {
        return user != null ? user.getEmail() : "Unknown Email";
    }

    public String getBookingDisplay() {
        return String.format("Booking %s: %s (%d seats) - %s",
                bookingReference,
                getMovieTitle(),
                seatsBooked,
                bookingStatus.getDisplayName());
    }

    // Booking status enum
    public enum BookingStatus {
        CONFIRMED("Confirmed"),
        CANCELLED("Cancelled");

        private final String displayName;

        BookingStatus(String displayName) {
            this.displayName = displayName;
        }

        public String getDisplayName() {
            return displayName;
        }
    }
}